import pandas as pd
import xlsxwriter
from xlsxwriter.utility import xl_range
from typing import List, Dict

class FinancialReporter:
    def __init__(self, output_path: str):
        self.output_path = output_path
        self.writer = pd.ExcelWriter(output_path, engine='xlsxwriter')
        self.workbook = self.writer.book
        
        # --- Define Styles ---
        self.header_format = self.workbook.add_format({
            'bold': True, 
            'text_wrap': True, 
            'valign': 'vcenter', 
            'align': 'center',
            'fg_color': '#4F81BD', 
            'font_color': 'white',
            'border': 1
        })
        
        self.metric_name_format = self.workbook.add_format({
            'bold': True,
            'border': 1,
            'bg_color': '#F2F2F2'
        })
        
        self.currency_format = self.workbook.add_format({
            'num_format': '#,##0', 
            'border': 1
        })
        
        self.percent_format = self.workbook.add_format({
            'num_format': '0.0%', 
            'border': 1
        })
        
        self.text_format = self.workbook.add_format({'border': 1})
        
        self.title_format = self.workbook.add_format({
            'bold': True, 
            'font_size': 16,
            'font_color': '#366092'
        })
        
        self.subtitle_format = self.workbook.add_format({
            'italic': True, 
            'font_size': 11,
            'font_color': '#595959'
        })
        
        # Conditional formatting style (Red text/bg for negative)
        self.neg_format = self.workbook.add_format({
            'font_color': '#9C0006', 
            'bg_color': '#FFC7CE'
        })

    def determine_format(self, metric_name: str):
        """Returns the appropriate Excel format based on the metric name."""
        lower_name = metric_name.lower()
        if any(x in lower_name for x in ['margin', 'growth', 'ratio', 'roe']):
            return self.percent_format
        return self.currency_format

    def create_dashboard(self, df: pd.DataFrame, company_info: Dict):
        worksheet = self.workbook.add_worksheet('Dashboard')
        chart_sheet = self.workbook.add_worksheet('ChartData')
        chart_sheet.hide()
        
        # Hide gridlines for a cleaner look
        worksheet.hide_gridlines(2)
        
        # --- 1. Prepare Data ---
        
        # Fix Year Column: Don't overwrite if it exists and has values, otherwise derive from period_end_date
        if 'Year' not in df.columns or df['Year'].isnull().any():
            if 'period_end_date' in df.columns:
                # Only fill NaN Years
                df['Year'] = df['Year'].fillna(pd.to_datetime(df['period_end_date']).dt.year)
        
        # Ensure Year is Integer
        df = df.dropna(subset=['Year']) # Drop rows where Year is still NaN
        df['Year'] = df['Year'].astype(int)
        
        # Split into Historical (for Table) and Full (for Chart)
        # Assuming 'type' column exists from forecaster, or infer from missing other metrics
        if 'type' in df.columns:
            historical_df = df[df['type'] != 'Forecast'].copy()
        else:
            historical_df = df.copy()
            
        # --- 2. Write Main Table (Historical Only) ---
        
        # Filter out metadata columns to keep only metrics
        metadata_cols = ['period_end_date', 'company_name', 'currency', 'reporting_unit', 'Year', 'type']
        metric_cols = [c for c in historical_df.columns if c not in metadata_cols]
        
        # Transpose: Index=Metrics, Columns=Years
        df_transposed = historical_df.set_index('Year')[metric_cols].T
        df_transposed = df_transposed.sort_index(axis=1)
        
        # Write Headers (Company Info)
        company_name = company_info.get('company_name', 'Unknown Company')
        currency = company_info.get('currency', 'N/A')
        unit = company_info.get('reporting_unit', 'thousands')
        
        worksheet.write('B2', f"{company_name} - Financial Dashboard", self.title_format)
        worksheet.write('B3', f"Reporting Currency: {currency} (in {unit}) | Generated by Financial Agent", self.subtitle_format)
        
        # Write Table Header (Years)
        start_row = 5
        start_col = 1 # Column B
        
        worksheet.write(start_row, start_col, "Metric", self.header_format)
        years = df_transposed.columns.tolist()
        for i, year in enumerate(years):
            worksheet.write(start_row, start_col + 1 + i, year, self.header_format)
            
        # Write "Trend (5Y)" Header
        trend_col = start_col + 1 + len(years)
        worksheet.write(start_row, trend_col, "Trend", self.header_format)
        
        # Write Data Rows
        for i, (metric, row_data) in enumerate(df_transposed.iterrows()):
            current_row = start_row + 1 + i
            
            # Write Metric Name
            display_name = metric.replace('_', ' ').title()
            worksheet.write(current_row, start_col, display_name, self.metric_name_format)
            
            # Determine format
            cell_format = self.determine_format(metric)
            
            # Write values
            row_values = row_data.tolist()
            for j, val in enumerate(row_values):
                col_idx = start_col + 1 + j
                if pd.isna(val):
                    worksheet.write(current_row, col_idx, "-", self.text_format)
                else:
                    worksheet.write(current_row, col_idx, val, cell_format)
            
            # Add Sparklines (Historical Trend)
            if len(years) > 1:
                data_range = xl_range(current_row, start_col + 1, current_row, start_col + len(years))
                worksheet.add_sparkline(current_row, trend_col, {
                    'range': data_range,
                    'type': 'line',
                    'style': 12,
                    'markers': True
                })
                worksheet.write(current_row, trend_col, "", self.text_format)
            else:
                worksheet.write(current_row, trend_col, "N/A", self.text_format)

        # Conditional Formatting
        first_data_row = start_row + 1
        last_data_row = start_row + len(df_transposed)
        first_data_col = start_col + 1
        last_data_col = start_col + len(years)
        
        if last_data_col >= first_data_col:
            worksheet.conditional_format(first_data_row, first_data_col, last_data_row, last_data_col,
                                         {'type': 'cell', 'criteria': '<', 'value': 0, 'format': self.neg_format})
                                      
        # Adjust Column Widths
        worksheet.set_column(start_col, start_col, 30)
        worksheet.set_column(first_data_col, last_data_col, 15)
        worksheet.set_column(trend_col, trend_col, 15)
        
        # --- 3. Create Revenue Chart (Historical + Forecast) ---
        
        # Prepare Chart Data (Year, Revenue)
        chart_df = df[['Year', 'revenue']].sort_values('Year')
        
        # Write Chart Data to Hidden Sheet
        chart_sheet.write_row('A1', ['Year', 'Revenue'])
        # Handle NaNs and convert to list
        years_list = chart_df['Year'].fillna(0).astype(int).tolist()
        revenue_list = chart_df['revenue'].fillna(0).tolist()
        
        chart_sheet.write_column('A2', years_list)
        chart_sheet.write_column('B2', revenue_list)
        
        # Create Chart
        chart = self.workbook.add_chart({'type': 'line'})
        
        num_rows = len(chart_df)
        
        chart.add_series({
            'name':       'Revenue Forecast',
            'categories': ['ChartData', 1, 0, num_rows, 0], # A2:A_end
            'values':     ['ChartData', 1, 1, num_rows, 1], # B2:B_end
            'line':       {'color': '#4F81BD', 'width': 2.25},
            'marker':     {'type': 'circle', 'size': 5}
        })
        
        chart.set_title({'name': 'Revenue Forecast (Historical + 5Y Projection)'})
        chart.set_x_axis({'name': 'Year'})
        chart.set_y_axis({'name': 'Revenue', 'major_gridlines': {'visible': True}})
        chart.set_legend({'position': 'bottom'})
        
        # Insert Chart below the table
        chart_row = last_data_row + 3
        worksheet.insert_chart(chart_row, start_col, chart, {'x_scale': 2, 'y_scale': 1.5})
        
        # Close
        try:
            # self.writer.close() calls self.workbook.close() but let's be explicit and check for errors
            self.workbook.close() 
            self.writer.close()
            print(f"Excel dashboard saved to: {self.output_path}")
        except PermissionError:
            print(f"⚠️ Permission denied: Could not write to {self.output_path}. File might be open.")
            new_path = self.output_path.replace(".xlsx", "_new.xlsx")
            print(f"🔄 Saving to alternative path: {new_path}")
            # Re-init logic is flawed here as we can't easily move the workbook. 
            # Ideally we should fail or retry the whole process.
            # For now, let's just raise to see the error.
            raise
        except Exception as e:
            print(f"❌ Error saving Excel file: {e}")
            raise

def generate_excel_report(df: pd.DataFrame, output_path: str) -> str:
    """
    Wrapper function to maintain compatibility with main.py.
    Instantiates FinancialReporter and creates the dashboard.
    """
    if df.empty:
        print("Warning: DataFrame is empty. Skipping Excel generation.")
        return
        
    # Extract company info from the first row of the DataFrame
    company_info = {
        'company_name': df['company_name'].iloc[0] if 'company_name' in df.columns else 'Unknown Company',
        'currency': df['currency'].iloc[0] if 'currency' in df.columns else 'N/A',
        'reporting_unit': df['reporting_unit'].iloc[0] if 'reporting_unit' in df.columns else 'thousands'
    }
    
    try:
        reporter = FinancialReporter(output_path)
        reporter.create_dashboard(df, company_info)
        return output_path
    except PermissionError:
        print(f"⚠️ Permission denied: {output_path} is open.")
        new_path = output_path.replace(".xlsx", f"_{pd.Timestamp.now().strftime('%H%M%S')}.xlsx")
        print(f"🔄 Retrying with new filename: {new_path}")
        reporter = FinancialReporter(new_path)
        reporter.create_dashboard(df, company_info)
        return new_path

if __name__ == "__main__":
    # Test block
    from datetime import date
    
    data = {
        'period_end_date': [date(2024, 12, 31), date(2023, 12, 31), date(2022, 12, 31)],
        'company_name': ['CD PROJEKT', 'CD PROJEKT', 'CD PROJEKT'],
        'currency': ['PLN', 'PLN', 'PLN'],
        'revenue': [985030, 1230199, 800000],
        'revenue_growth_yoy': [-0.19, 0.53, 0.1],
        'ebit': [365496, 469040, 300000],
        'ebit_margin': [0.37, 0.38, 0.375],
        'net_income': [469874, 481105, 350000],
        'net_income_growth_yoy': [-0.02, 0.37, 0.1],
        'net_margin': [0.47, 0.39, 0.43],
        'assets': [3042424, 2613500, 2000000],
        'equity': [2800667, 2403223, 1800000],
        'roe': [0.16, 0.20, 0.19]
    }
    df = pd.DataFrame(data)
    generate_excel_report(df, "test_dashboard.xlsx")
