import pandas as pd
import xlsxwriter
from xlsxwriter.utility import xl_range
from typing import List, Dict

class FinancialReporter:
    def __init__(self, output_path: str):
        self.output_path = output_path
        self.writer = pd.ExcelWriter(output_path, engine='xlsxwriter')
        self.workbook = self.writer.book
        
        # --- Define Styles ---
        self.header_format = self.workbook.add_format({
            'bold': True, 
            'text_wrap': True, 
            'valign': 'vcenter', 
            'align': 'center',
            'fg_color': '#4F81BD', 
            'font_color': 'white',
            'border': 1
        })
        
        self.metric_name_format = self.workbook.add_format({
            'bold': True,
            'border': 1,
            'bg_color': '#F2F2F2'
        })
        
        self.currency_format = self.workbook.add_format({
            'num_format': '#,##0', 
            'border': 1
        })
        
        self.percent_format = self.workbook.add_format({
            'num_format': '0.0%', 
            'border': 1
        })
        
        self.text_format = self.workbook.add_format({'border': 1})
        
        self.title_format = self.workbook.add_format({
            'bold': True, 
            'font_size': 16,
            'font_color': '#366092'
        })
        
        self.subtitle_format = self.workbook.add_format({
            'italic': True, 
            'font_size': 11,
            'font_color': '#595959'
        })
        
        # Conditional formatting style (Red text/bg for negative)
        self.neg_format = self.workbook.add_format({
            'font_color': '#9C0006', 
            'bg_color': '#FFC7CE'
        })

    def determine_format(self, metric_name: str):
        """Returns the appropriate Excel format based on the metric name."""
        lower_name = metric_name.lower()
        if any(x in lower_name for x in ['margin', 'growth', 'ratio', 'roe']):
            return self.percent_format
        return self.currency_format

    def create_dashboard(self, df: pd.DataFrame, company_info: Dict):
        worksheet = self.workbook.add_worksheet('Dashboard')
        chart_sheet = self.workbook.add_worksheet('ChartData')
        chart_sheet.hide()
        
        # Hide gridlines for a cleaner look
        worksheet.hide_gridlines(2)
        
        # --- 1. Prepare Data ---
        
        # Fix Year Column: Don't overwrite if it exists and has values, otherwise derive from period_end_date
        if 'Year' not in df.columns or df['Year'].isnull().any():
            if 'period_end_date' in df.columns:
                # Only fill NaN Years
                df['Year'] = df['Year'].fillna(pd.to_datetime(df['period_end_date']).dt.year)
        
        # Ensure Year is Integer
        df = df.dropna(subset=['Year']) # Drop rows where Year is still NaN
        df['Year'] = df['Year'].astype(int)
        
        # Split into Historical (for Table) and Full (for Chart)
        # Assuming 'type' column exists from forecaster, or infer from missing other metrics
        if 'type' in df.columns:
            historical_df = df[df['type'] != 'Forecast'].copy()
        else:
            historical_df = df.copy()
            
        # --- 2. Write Main Table (Historical Only) ---
        
        # Filter out metadata columns to keep only metrics
        metadata_cols = ['period_end_date', 'company_name', 'currency', 'reporting_unit', 'Year', 'type']
        metric_cols = [c for c in historical_df.columns if c not in metadata_cols]
        
        # Transpose: Index=Metrics, Columns=Years
        df_transposed = historical_df.set_index('Year')[metric_cols].T
        df_transposed = df_transposed.sort_index(axis=1)
        
        # Write Headers (Company Info)
        company_name = company_info.get('company_name', 'Unknown Company')
        currency = company_info.get('currency', 'N/A')
        unit = company_info.get('reporting_unit', 'thousands')
        
        worksheet.write('B2', f"{company_name} - Financial Dashboard", self.title_format)
        worksheet.write('B3', f"Reporting Currency: {currency} (in {unit}) | Generated by Financial Agent", self.subtitle_format)
        
        # Write Table Header (Years)
        start_row = 5
        start_col = 1 # Column B
        
        worksheet.write(start_row, start_col, "Metric", self.header_format)
        years = df_transposed.columns.tolist()
        for i, year in enumerate(years):
            worksheet.write(start_row, start_col + 1 + i, year, self.header_format)
            
        # Write "Trend (5Y)" Header
        trend_col = start_col + 1 + len(years)
        worksheet.write(start_row, trend_col, "Trend", self.header_format)
        
        # Write Data Rows
        for i, (metric, row_data) in enumerate(df_transposed.iterrows()):
            current_row = start_row + 1 + i
            
            # Write Metric Name
            display_name = metric.replace('_', ' ').title()
            worksheet.write(current_row, start_col, display_name, self.metric_name_format)
            
            # Determine format
            cell_format = self.determine_format(metric)
            
            # Write values
            row_values = row_data.tolist()
            for j, val in enumerate(row_values):
                col_idx = start_col + 1 + j
                if pd.isna(val):
                    worksheet.write(current_row, col_idx, "-", self.text_format)
                else:
                    worksheet.write(current_row, col_idx, val, cell_format)
            
            # Add Sparklines (Historical Trend)
            if len(years) > 1:
                data_range = xl_range(current_row, start_col + 1, current_row, start_col + len(years))
                worksheet.add_sparkline(current_row, trend_col, {
                    'range': data_range,
                    'type': 'line',
                    'style': 12,
                    'markers': True
                })
                worksheet.write(current_row, trend_col, "", self.text_format)
            else:
                worksheet.write(current_row, trend_col, "N/A", self.text_format)

        # Conditional Formatting
        first_data_row = start_row + 1
        last_data_row = start_row + len(df_transposed)
        first_data_col = start_col + 1
        last_data_col = start_col + len(years)
        
        if last_data_col >= first_data_col:
            worksheet.conditional_format(first_data_row, first_data_col, last_data_row, last_data_col,
                                         {'type': 'cell', 'criteria': '<', 'value': 0, 'format': self.neg_format})
                                      
        # Adjust Column Widths
        worksheet.set_column(start_col, start_col, 30)
        worksheet.set_column(first_data_col, last_data_col, 15)
        worksheet.set_column(trend_col, trend_col, 15)
        
        # --- 3. Create Revenue Chart (Historical + Forecast) ---
        
        # Prepare Chart Data (Year, Revenue)
        chart_df = df[['Year', 'revenue']].sort_values('Year')
        
        # Write Chart Data to Hidden Sheet
        chart_sheet.write_row('A1', ['Year', 'Revenue'])
        # Handle NaNs and convert to list
        years_list = chart_df['Year'].fillna(0).astype(int).tolist()
        revenue_list = chart_df['revenue'].fillna(0).tolist()
        
        chart_sheet.write_column('A2', years_list)
        chart_sheet.write_column('B2', revenue_list)
        
        # Create Chart
        chart = self.workbook.add_chart({'type': 'line'})
        
        num_rows = len(chart_df)
        
        chart.add_series({
            'name':       'Revenue Forecast',
            'categories': ['ChartData', 1, 0, num_rows, 0], # A2:A_end
            'values':     ['ChartData', 1, 1, num_rows, 1], # B2:B_end
            'line':       {'color': '#4F81BD', 'width': 2.25},
            'marker':     {'type': 'circle', 'size': 5}
        })
        
        chart.set_title({'name': 'Revenue Forecast (Historical + 5Y Projection)'})
        chart.set_x_axis({'name': 'Year'})
        chart.set_y_axis({'name': 'Revenue', 'major_gridlines': {'visible': True}})
        chart.set_legend({'position': 'bottom'})
        
        # Insert Chart below the table
        chart_row = last_data_row + 3
        worksheet.insert_chart(chart_row, start_col, chart, {'x_scale': 2, 'y_scale': 1.5})
        
        # --- 4. DCF Valuation Model (Glass Box) ---
        
        dcf_start_row = chart_row + 25 # Place below chart
        
        # Section Header
        worksheet.write(dcf_start_row, start_col, "DCF Valuation Model", self.title_format)
        worksheet.write(dcf_start_row + 1, start_col, "Assumptions & Inputs (Editable)", self.subtitle_format)
        
        # -- Assumptions Block --
        assumptions_row = dcf_start_row + 3
        
        # Input Style (Yellow Background)
        input_format = self.workbook.add_format({
            'bg_color': '#FFFFCC',
            'border': 1,
            'num_format': '0.0%'
        })
        
        # WACC
        worksheet.write(assumptions_row, start_col, "WACC", self.metric_name_format)
        worksheet.write(assumptions_row, start_col + 1, company_info.get('wacc', 0.10), input_format)
        wacc_cell = xl_range(assumptions_row, start_col + 1, assumptions_row, start_col + 1)
        
        # Terminal Growth
        worksheet.write(assumptions_row + 1, start_col, "Terminal Growth", self.metric_name_format)
        worksheet.write(assumptions_row + 1, start_col + 1, company_info.get('terminal_growth', 0.025), input_format)
        g_cell = xl_range(assumptions_row + 1, start_col + 1, assumptions_row + 1, start_col + 1)
        
        # Tax Rate
        worksheet.write(assumptions_row + 2, start_col, "Tax Rate", self.metric_name_format)
        worksheet.write(assumptions_row + 2, start_col + 1, 0.19, input_format)
        tax_rate_cell = xl_range(assumptions_row + 2, start_col + 1, assumptions_row + 2, start_col + 1)
        
        # EBIT Margin Assumption (Last Historical)
        # DEBUG: Print historical df info to debug missing values
        print("DEBUG: Historical DF Shape:", historical_df.shape)
        if not historical_df.empty and 'ebit_margin' in historical_df.columns:
            last_hist_ebit_margin = float(historical_df['ebit_margin'].iloc[0])
            print(f"DEBUG: Extracted EBIT Margin from history: {last_hist_ebit_margin}")
        else:
            last_hist_ebit_margin = 0.10
            print("DEBUG: Using default EBIT Margin 0.10")

        # Safeguard: If margin is 0 (likely error), default to 10%
        if abs(last_hist_ebit_margin) < 0.001: 
            print("DEBUG: Margin too small, resetting to 0.10")
            last_hist_ebit_margin = 0.10
            
        worksheet.write(assumptions_row, start_col + 3, "EBIT Margin (Proj)", self.metric_name_format)
        worksheet.write(assumptions_row, start_col + 4, last_hist_ebit_margin, input_format)
        ebit_margin_cell = xl_range(assumptions_row, start_col + 4, assumptions_row, start_col + 4)
        
        # D&A % Revenue Assumption (Last Historical)
        # Calculate D&A % from last historical year
        last_hist_rev = float(historical_df['revenue'].iloc[0]) if not historical_df.empty else 0
        last_hist_da = float(historical_df['ebitda'].iloc[0] - historical_df['ebit'].iloc[0]) if not historical_df.empty and 'ebitda' in historical_df.columns else 0
        
        if last_hist_rev > 0:
            da_percent = last_hist_da / last_hist_rev
        else:
            da_percent = 0.05
        
        worksheet.write(assumptions_row + 1, start_col + 3, "D&A % Rev", self.metric_name_format)
        worksheet.write(assumptions_row + 1, start_col + 4, da_percent, input_format)
        da_percent_cell = xl_range(assumptions_row + 1, start_col + 4, assumptions_row + 1, start_col + 4)
        
        # Capex % Revenue Assumption (Assume equal to D&A for maintenance)
        worksheet.write(assumptions_row + 2, start_col + 3, "Capex % Rev", self.metric_name_format)
        worksheet.write(assumptions_row + 2, start_col + 4, da_percent, input_format)
        capex_percent_cell = xl_range(assumptions_row + 2, start_col + 4, assumptions_row + 2, start_col + 4)

        # -- Projection Table --
        proj_start_row = assumptions_row + 5
        
        # Get Forecast Data
        forecast_df = df[df['type'] == 'Forecast'].sort_values('Year')
        if forecast_df.empty:
             # Fallback if no forecast
             forecast_years = []
        else:
             forecast_years = forecast_df['Year'].tolist()
             forecast_revenue = forecast_df['revenue'].tolist()

        # Headers
        worksheet.write(proj_start_row, start_col, "Metric", self.header_format)
        for i, year in enumerate(forecast_years):
            worksheet.write(proj_start_row, start_col + 1 + i, year, self.header_format)
            
        # Rows
        metrics = ['Revenue', 'EBIT', 'Tax', 'NOPAT', 'Plus D&A', 'Less Capex', 'Free Cash Flow']
        
        # Helper for column letters (Data starts at start_col + 1)
        from xlsxwriter.utility import xl_col_to_name, xl_rowcol_to_cell
        
        # 1. Revenue (Hardcoded from Forecast)
        row = proj_start_row + 1
        worksheet.write(row, start_col, "Revenue", self.metric_name_format)
        for i, val in enumerate(forecast_revenue):
            worksheet.write(row, start_col + 1 + i, val, self.currency_format)
        rev_row_idx = row + 1 # 1-based index for formulas
            
        # 2. EBIT (Formula)
        row += 1
        worksheet.write(row, start_col, "EBIT", self.metric_name_format)
        for i in range(len(forecast_years)):
            col_letter = xl_col_to_name(start_col + 1 + i)
            # Formula: =Revenue * $EBIT_Margin_Cell
            # Use absolute reference for margin cell
            margin_ref = xl_rowcol_to_cell(assumptions_row, start_col + 4, row_abs=True, col_abs=True)
            formula = f"={col_letter}{rev_row_idx}*{margin_ref}"
            worksheet.write_formula(row, start_col + 1 + i, formula, self.currency_format)
        ebit_row_idx = row + 1
            
        # 3. Tax (Formula)
        row += 1
        worksheet.write(row, start_col, "Tax", self.metric_name_format)
        for i in range(len(forecast_years)):
            col_letter = xl_col_to_name(start_col + 1 + i)
            # Formula: =EBIT * $Tax_Rate_Cell
            tax_ref = xl_rowcol_to_cell(assumptions_row + 2, start_col + 1, row_abs=True, col_abs=True)
            formula = f"={col_letter}{ebit_row_idx}*{tax_ref}"
            worksheet.write_formula(row, start_col + 1 + i, formula, self.currency_format)
        tax_row_idx = row + 1
            
        # 4. NOPAT (Formula)
        row += 1
        worksheet.write(row, start_col, "NOPAT", self.metric_name_format)
        for i in range(len(forecast_years)):
            col_letter = xl_col_to_name(start_col + 1 + i)
            # Formula: =EBIT - Tax
            formula = f"={col_letter}{ebit_row_idx}-{col_letter}{tax_row_idx}"
            worksheet.write_formula(row, start_col + 1 + i, formula, self.currency_format)
        nopat_row_idx = row + 1
        
        # 5. Plus D&A (Formula)
        row += 1
        worksheet.write(row, start_col, "Plus D&A", self.metric_name_format)
        for i in range(len(forecast_years)):
            col_letter = xl_col_to_name(start_col + 1 + i)
            # Formula: =Revenue * $DA_Percent_Cell
            da_ref = xl_rowcol_to_cell(assumptions_row + 1, start_col + 4, row_abs=True, col_abs=True)
            formula = f"={col_letter}{rev_row_idx}*{da_ref}"
            worksheet.write_formula(row, start_col + 1 + i, formula, self.currency_format)
        da_row_idx = row + 1
        
        # 6. Less Capex (Formula)
        row += 1
        worksheet.write(row, start_col, "Less Capex", self.metric_name_format)
        for i in range(len(forecast_years)):
            col_letter = xl_col_to_name(start_col + 1 + i)
            # Formula: =Revenue * $Capex_Percent_Cell
            capex_ref = xl_rowcol_to_cell(assumptions_row + 2, start_col + 4, row_abs=True, col_abs=True)
            formula = f"={col_letter}{rev_row_idx}*{capex_ref}"
            worksheet.write_formula(row, start_col + 1 + i, formula, self.currency_format)
        capex_row_idx = row + 1
            
        # 7. FCF (Formula)
        row += 1
        worksheet.write(row, start_col, "Free Cash Flow", self.metric_name_format)
        fcf_cells = []
        for i in range(len(forecast_years)):
            col_letter = xl_col_to_name(start_col + 1 + i)
            # Formula: =NOPAT + D&A - Capex
            formula = f"={col_letter}{nopat_row_idx}+{col_letter}{da_row_idx}-{col_letter}{capex_row_idx}"
            worksheet.write_formula(row, start_col + 1 + i, formula, self.currency_format)
            fcf_cells.append(f"{col_letter}{row+1}")
        fcf_row_idx = row + 1
            
        # -- Valuation --
        val_start_row = row + 3
        
        worksheet.write(val_start_row, start_col, "Discount Period", self.metric_name_format)
        worksheet.write(val_start_row + 1, start_col, "Discount Factor", self.metric_name_format)
        worksheet.write(val_start_row + 2, start_col, "PV of FCF", self.metric_name_format)
        
        pv_cells = []
        last_fcf_cell = fcf_cells[-1] if fcf_cells else "B1"
        last_discount_factor_cell = "B1"
        
        # WACC Reference
        wacc_ref = xl_rowcol_to_cell(assumptions_row, start_col + 1, row_abs=True, col_abs=True)
        
        for i in range(len(forecast_years)):
            col_letter = xl_col_to_name(start_col + 1 + i)
            period = i + 1
            
            # Period
            worksheet.write(val_start_row, start_col + 1 + i, period, self.text_format)
            
            # Discount Factor: =1/(1+WACC)^Period
            df_formula = f"=1/(1+{wacc_ref})^{period}"
            worksheet.write_formula(val_start_row + 1, start_col + 1 + i, df_formula, self.workbook.add_format({'num_format': '0.000', 'border': 1}))
            
            # PV of FCF: =FCF * Discount Factor
            pv_formula = f"={col_letter}{fcf_row_idx}*{col_letter}{val_start_row + 2}"
            worksheet.write_formula(val_start_row + 2, start_col + 1 + i, pv_formula, self.currency_format)
            
            pv_cells.append(f"{col_letter}{val_start_row + 3}")
            if i == len(forecast_years) - 1:
                last_discount_factor_cell = f"{col_letter}{val_start_row + 2}"

        # Terminal Value
        tv_row = val_start_row + 4
        worksheet.write(tv_row, start_col, "Terminal Value (TV)", self.metric_name_format)
        
        # TV Formula: =Last_FCF * (1+g) / (WACC - g)
        g_ref = xl_rowcol_to_cell(assumptions_row + 1, start_col + 1, row_abs=True, col_abs=True)
        tv_formula = f"={last_fcf_cell}*(1+{g_ref})/({wacc_ref}-{g_ref})"
        worksheet.write_formula(tv_row, start_col + 1, tv_formula, self.currency_format)
        tv_cell = f"{chr(ord('B'))}{tv_row+1}" # This is wrong, column B is Metric name. TV is usually in the last column or separate.
        # Let's put TV value in the column next to Metric name (Start_Col + 1)
        tv_cell = f"{xl_col_to_name(start_col + 1)}{tv_row+1}"
        
        # PV of TV
        worksheet.write(tv_row + 1, start_col, "PV of TV", self.metric_name_format)
        pv_tv_formula = f"={tv_cell}*{last_discount_factor_cell}"
        worksheet.write_formula(tv_row + 1, start_col + 1, pv_tv_formula, self.currency_format)
        pv_tv_cell = f"{xl_col_to_name(start_col + 1)}{tv_row+2}"
        
        # Enterprise Value
        ev_row = tv_row + 3
        ev_format = self.workbook.add_format({
            'bold': True, 
            'bg_color': '#DCE6F1', 
            'border': 1, 
            'num_format': '#,##0',
            'font_size': 12
        })
        
        worksheet.write(ev_row, start_col, "Estimated Enterprise Value", ev_format)
        
        # Sum of PVs + PV of TV
        sum_range = f"{pv_cells[0]}:{pv_cells[-1]}" if pv_cells else "B1"
        ev_formula = f"=SUM({sum_range})+{pv_tv_cell}"
        worksheet.write_formula(ev_row, start_col + 1, ev_formula, ev_format)
        ev_cell = f"{xl_col_to_name(start_col + 1)}{ev_row+1}"
        
        # -- Equity Value Bridge --
        bridge_start_row = ev_row + 2
        
        # Get latest historical data for Bridge
        # We assume the first row of historical_df is the latest year (sorted descending usually, but let's check)
        # Actually, in create_dashboard, we sorted by Year ascending for charts, but historical_df comes from df[df['type']=='Historical'].
        # Let's ensure we get the latest year.
        latest_hist = historical_df.sort_values('Year', ascending=False).iloc[0] if not historical_df.empty else None
        
        latest_debt = latest_hist['total_debt'] if latest_hist is not None and 'total_debt' in latest_hist else 0
        latest_cash = latest_hist['cash_and_equivalents'] if latest_hist is not None and 'cash_and_equivalents' in latest_hist else 0
        latest_shares = latest_hist['shares_outstanding'] if latest_hist is not None and 'shares_outstanding' in latest_hist else 1 # Avoid div/0
        
        # 1. Less: Net Debt
        # Net Debt = Total Debt - Cash
        # If Cash > Debt, Net Debt is negative, so subtracting it adds to Equity Value. Correct.
        net_debt_row = bridge_start_row
        worksheet.write(net_debt_row, start_col, "Less: Net Debt", self.metric_name_format)
        
        # We'll write the formula: =Debt - Cash
        # But since these are point-in-time values from history, we can just write the value or put them in cells.
        # Let's put Debt and Cash in the Assumptions block or just hardcode the Net Debt calculation here for simplicity,
        # OR better, write Debt and Cash cells and reference them.
        # Let's write them explicitly here for transparency.
        
        worksheet.write(net_debt_row, start_col + 3, "Total Debt", self.text_format)
        worksheet.write(net_debt_row, start_col + 4, latest_debt, self.currency_format)
        debt_cell = f"{xl_col_to_name(start_col + 4)}{net_debt_row+1}"
        
        worksheet.write(net_debt_row + 1, start_col + 3, "Cash", self.text_format)
        worksheet.write(net_debt_row + 1, start_col + 4, latest_cash, self.currency_format)
        cash_cell = f"{xl_col_to_name(start_col + 4)}{net_debt_row+2}"
        
        # Net Debt Formula: =Debt - Cash
        net_debt_formula = f"={debt_cell}-{cash_cell}"
        worksheet.write_formula(net_debt_row, start_col + 1, net_debt_formula, self.currency_format)
        net_debt_cell = f"{xl_col_to_name(start_col + 1)}{net_debt_row+1}"
        
        # 2. Estimated Equity Value
        eq_row = net_debt_row + 1
        worksheet.write(eq_row, start_col, "Estimated Equity Value", self.metric_name_format)
        # Formula: =EV - Net Debt
        eq_formula = f"={ev_cell}-{net_debt_cell}"
        worksheet.write_formula(eq_row, start_col + 1, eq_formula, self.currency_format)
        eq_cell = f"{xl_col_to_name(start_col + 1)}{eq_row+1}"
        
        # 3. Shares Outstanding
        shares_row = eq_row + 2
        worksheet.write(shares_row, start_col, "Shares Outstanding", self.metric_name_format)
        worksheet.write(shares_row, start_col + 1, latest_shares, self.workbook.add_format({'num_format': '#,##0', 'border': 1}))
        shares_cell = f"{xl_col_to_name(start_col + 1)}{shares_row+1}"
        
        # 4. Implied Share Price
        price_row = shares_row + 1
        price_format = self.workbook.add_format({
            'bold': True, 
            'font_color': '#0000FF', # Blue
            'font_size': 14,
            'border': 1, 
            'num_format': '0.00'
        })
        
        # Get date string for label
        val_date_str = latest_hist['period_end_date'].strftime('%Y-%m-%d') if latest_hist is not None and 'period_end_date' in latest_hist else "Unknown Date"
        
        worksheet.write(price_row, start_col, f"Implied Share Price (PLN) [As of {val_date_str}]", self.metric_name_format)
        
        # Determine Multiplier based on Reporting Unit
        # Equity Value is in the table's currency unit. Shares are in Units.
        # We need to convert Equity Value to Units (numerator) before dividing by Shares.
        rep_unit = str(company_info.get('reporting_unit', 'thousands')).lower()
        
        if 'thousand' in rep_unit:
            unit_mult = 1000
        elif 'million' in rep_unit:
            unit_mult = 1_000_000
        else:
            unit_mult = 1
            
        print(f"DEBUG: Reporting Unit: {rep_unit}, Multiplier: {unit_mult}")

        # Formula: =Equity Value * Multiplier / Shares
        if unit_mult == 1:
             price_formula = f"={eq_cell}/{shares_cell}"
        else:
             price_formula = f"={eq_cell}*{unit_mult}/{shares_cell}"
             
        worksheet.write_formula(price_row, start_col + 1, price_formula, price_format)
        
        # Close
        try:
            # Only call close on the writer, which handles the workbook internally
            self.writer.close()
            print(f"Excel dashboard saved to: {self.output_path}")
        except PermissionError:
            print(f"⚠️ Permission denied: Could not write to {self.output_path}. File might be open.")
            new_path = self.output_path.replace(".xlsx", "_new.xlsx")
            print(f"🔄 Saving to alternative path: {new_path}")
            # Re-init logic is flawed here as we can't easily move the workbook. 
            # Ideally we should fail or retry the whole process.
            # For now, let's just raise to see the error.
            raise
        except Exception as e:
            print(f"❌ Error saving Excel file: {e}")
            raise

def generate_excel_report(df: pd.DataFrame, output_path: str, wacc: float = 0.10, terminal_growth: float = 0.025) -> str:
    """
    Wrapper function to maintain compatibility with main.py.
    Instantiates FinancialReporter and creates the dashboard.
    """
    if df.empty:
        print("Warning: DataFrame is empty. Skipping Excel generation.")
        return
        
    # Extract company info from the first row of the DataFrame
    company_info = {
        'company_name': df['company_name'].iloc[0] if 'company_name' in df.columns else 'Unknown Company',
        'currency': df['currency'].iloc[0] if 'currency' in df.columns else 'N/A',
        'reporting_unit': df['reporting_unit'].iloc[0] if 'reporting_unit' in df.columns else 'thousands',
        'wacc': wacc,
        'terminal_growth': terminal_growth
    }
    
    try:
        reporter = FinancialReporter(output_path)
        reporter.create_dashboard(df, company_info)
        return output_path
    except PermissionError:
        print(f"⚠️ Permission denied: {output_path} is open.")
        new_path = output_path.replace(".xlsx", f"_{pd.Timestamp.now().strftime('%H%M%S')}.xlsx")
        print(f"🔄 Retrying with new filename: {new_path}")
        reporter = FinancialReporter(new_path)
        reporter.create_dashboard(df, company_info)
        return new_path

if __name__ == "__main__":
    # Test block
    from datetime import date
    
    data = {
        'period_end_date': [date(2024, 12, 31), date(2023, 12, 31), date(2022, 12, 31)],
        'company_name': ['CD PROJEKT', 'CD PROJEKT', 'CD PROJEKT'],
        'currency': ['PLN', 'PLN', 'PLN'],
        'revenue': [985030, 1230199, 800000],
        'revenue_growth_yoy': [-0.19, 0.53, 0.1],
        'ebit': [365496, 469040, 300000],
        'ebit_margin': [0.37, 0.38, 0.375],
        'net_income': [469874, 481105, 350000],
        'net_income_growth_yoy': [-0.02, 0.37, 0.1],
        'net_margin': [0.47, 0.39, 0.43],
        'assets': [3042424, 2613500, 2000000],
        'equity': [2800667, 2403223, 1800000],
        'roe': [0.16, 0.20, 0.19]
    }
    df = pd.DataFrame(data)
    generate_excel_report(df, "test_dashboard.xlsx")
